### PR TITLE
Installation instructions Ubuntu ppa

### PR DESCRIPTION
**Pull request by orschiro**

### CODE REVIEW

**Comment by hluk** [comment]
Great, thanks. I should try to simplify the command for Ubuntu, it looks a bit scary.

**Comment by orschiro** [comment]
Thanks for merging so quickly! :-)

A way of simplifying would be to offer a proper ppa: repository link,
correct?

**Comment by hluk** [comment]
@orschiro I tried to create PPA some years back but had some issues with it (not sure what it was anymore). I really should try again.

**Comment by orschiro** [comment]
Let me please know if I can somehow help (although I haven't created any
PPA myself yet)!

**Comment by hluk** [comment]
OK, I'll try to create a PPA and let you know how it goes.

BTW, I just noticed you're are not in list of developers for CopyQ (About dialog, [AUTHORS](https://github.com/hluk/CopyQ/blob/master/AUTHORS) file). Preposterous! Is it OK to mention you there? What e-mail address should I use?

**Comment by orschiro** [comment]
Perfect!

And thank you for your willingness to add me to the list. :-)

Please use this link: http://www.orzanna.de/email.png

**Comment by hluk** [comment]
OK, I've added you: a3125e72329a44e04ea4bfd89d71713453404e71

And PPA is finally up and running: https://launchpad.net/~hluk/+archive/ubuntu/copyq

**Comment by orschiro** [comment]
Thank you! :-)

Please see https://github.com/hluk/CopyQ/pull/663

**Pull request merged**
