### PR TITLE
Update copyq.iss

### PR DESCRIPTION
**Pull request by VenusGirl**

### CODE REVIEW

**Comment by VenusGirl** [comment]
There is no Korean.isl, so we can't proceed to the next one.

Please add it.
[INNO Setup - Korean.zip](https://github.com/hluk/CopyQ/files/10774283/INNO.Setup.-.Korean.zip)

**Comment by hluk** [comment]
> There is no Korean.isl, so we can't proceed to the next one.
> 
> Please add it. c:\program files (x86)\inno setup 6\Languages\Korean.isl
> 
> [INNO Setup - Korean.zip](https://github.com/hluk/CopyQ/files/10774283/INNO.Setup.-.Korean.zip)

The file would need to be **downloaded** (in Appveyor CI/CD) before the setup.exe is created: https://github.com/hluk/CopyQ/blob/968cb64e936293a7fd2d49baafed696ca8b34717/utils/appveyor/after_build.sh#L129

**Comment by hluk** [comment]
Ah, I could not find my previous comment; it is in the previously closed PR - I'm just linking this here: #2263

**Comment by hluk** [comment]
> > There is no Korean.isl, so we can't proceed to the next one.
> > Please add it. c:\program files (x86)\inno setup 6\Languages\Korean.isl
> > [INNO Setup - Korean.zip](https://github.com/hluk/CopyQ/files/10774283/INNO.Setup.-.Korean.zip)
> 
> The file would need to be **downloaded** (in Appveyor CI/CD) before the setup.exe is created:
> 
> https://github.com/hluk/CopyQ/blob/968cb64e936293a7fd2d49baafed696ca8b34717/utils/appveyor/after_build.sh#L129

I'm adding it in PR #2277.

**Pull request closed without merging**
