### PR TITLE
Build an App Bundle on macOS with CMake and CPack

### PR DESCRIPTION
**Pull request by briskycat**
Finishes the work started in #891
How to use:

1. `cmake --build . --target all --parallel`
2. `cpack`

You should get something like `CPack: - package: /.../copyq-3.7.3-76-g5f3a5138-Darwin.dmg generated.` at the end.

### CODE REVIEW

**Comment by briskycat** [comment]
Yes, I'll try.

**Comment by briskycat** [comment]
Done. 

Not sure why you have these
```
root=$PWD

...

cd "$root"
```
commands in the scripts (they don't make any sense to me as current working directory is not propagated to shell's parent process) but I left them as they were anyway.

**Comment by hluk** [comment]
Thanks, this helps a lot. I fixed the failing test (issue in fakevim plugin tests).

Can you also verify that the build binary doesn't use Qt libraries installed on system? I think following command should print Qt libs only from the app bundle (that's what the `macdeployqtfix` tool fixed before).

```bash
otool -L CopyQ.app/Contents/Frameworks/QtSvg.framework/Versions/5/QtSvg
```

For details see [this comment](https://github.com/hluk/CopyQ/issues/590#issuecomment-264120833).

Otherwise it looks good to merge. Thanks to this I'll no longer need to update and keep those obsolete *.pro files (I just need to figure out how to update translations).

**Comment by briskycat** [comment]
Added otool invocation to `script-osx.sh`. Also added a step to uninstall local qt5 before the tests.

**Comment by hluk** [comment]
Awesome! Thanks again.

**Pull request merged**
