### PR TITLE
Added apt-get install command

### PR DESCRIPTION
**Pull request by arthurkarganyan**

### CODE REVIEW

**Comment by hluk** [comment]
What about cmake package?

**Comment by arthurkarganyan** [comment]
Does it install all this packeges?

**Comment by hluk** [comment]
You need to install `cmake` explicitly since CopyQ is built using CMake.

You won't need `cmake` and `-dev` packages when CopyQ is installed from a package.

For reference [here is file for Debian package](https://build.opensuse.org/package/view_file/home:lukho:copyq/CopyQ/debian.control?expand=1). `Build-Depends` section lists packages needed to build and `Depends` lists packages needed to run CopyQ.

**Comment by arthurkarganyan** [comment]
Thanks! I sorry I didn't know.

**Pull request closed without merging**
