### PR TITLE
Fixes for Qt 6

### LINKED ISSUE #2323: Building with qt 6.5 fails
```
/build/source/src/scriptable/scriptableproxy.cpp: In member function 'QByteArray ScriptableProxy::callFunctionHelper(const QByteArray&)':
/build/source/src/scriptable/scriptableproxy.cpp:924:23: error: no match for 'operator=' (operand types are 'QGenericArgument' and 'QMetaMethodArgument')
  924 |             args[i] = Q_ARG(QVariant, value);
      |                       ^~~~~
/nix/store/q5fzqbgghqf8nr947h8rvn80smrlr4rg-qtbase-6.5.0-dev/include/QtCore/qobjectdefs.h:82:21: note: candidate: 'constexpr QGenericArgument& QGenericArgument::operator=(const QGenericArgument&)'
   82 | class Q_CORE_EXPORT QGenericArgument
      |                     ^~~~~~~~~~~~~~~~
/nix/store/q5fzqbgghqf8nr947h8rvn80smrlr4rg-qtbase-6.5.0-dev/include/QtCore/qobjectdefs.h:82:21: note:   no known conversion for argument 1 from 'QMetaMethodArgument' to 'const QGenericArgument&'
/nix/store/q5fzqbgghqf8nr947h8rvn80smrlr4rg-qtbase-6.5.0-dev/include/QtCore/qobjectdefs.h:82:21: note: candidate: 'constexpr QGenericArgument& QGenericArgument::operator=(QGenericArgument&&)'
/nix/store/q5fzqbgghqf8nr947h8rvn80smrlr4rg-qtbase-6.5.0-dev/include/QtCore/qobjectdefs.h:82:21: note:   no known conversion for argument 1 from 'QMetaMethodArgument' to 'QGenericArgument&&'
/build/source/src/scriptable/scriptableproxy.cpp:952:17: error: operands to '?:' have different types 'QGenericReturnArgument' and 'QMetaMethodReturnArgument'
  952 |                 ? QGenericReturnArgument(returnValue.typeName(), static_cast<void*>(returnValue.data()) )
      |                 ^
```

### PR DESCRIPTION
**Pull request by hluk**
Fixes #2323

### CODE REVIEW

**Review by Artturin — APPROVED** [review]
builds but i get

`
ERROR: Cannot load library /nix/store/13sxagadpsf3m26cn169gjd62rgabgnn-CopyQ-6.4.0/lib/copyq/plugins/libitemtags.so: (/nix/store/13sxagadpsf3m26cn169gjd62rgabgnn-CopyQ-6.4.0/lib/copyq/plugins/libitemtags.so: undefined symbol: _ZrsR11QDataStreamR7Command)
`

when launching but the program seems to work ok regardless. i'll report it in the nixpkgs qt 6.5 pr

**Comment by hluk** [comment]
> builds but i get
> 
> `ERROR: Cannot load library /nix/store/13sxagadpsf3m26cn169gjd62rgabgnn-CopyQ-6.4.0/lib/copyq/plugins/libitemtags.so: (/nix/store/13sxagadpsf3m26cn169gjd62rgabgnn-CopyQ-6.4.0/lib/copyq/plugins/libitemtags.so: undefined symbol: _ZrsR11QDataStreamR7Command)`
> 
> when launching but the program seems to work ok regardless. i'll report it in the nixpkgs qt 6.5 pr

Thanks for checking!

Plugins were missing some dependency (`command.cpp` - previously no code from the module was needed).

Fixing.

**Comment by hluk** [comment]
I've added couple more Qt 6 fixes and included Qt 6 build+tests in CI.

**Comment by Artturin** [comment]
i now get
```
Warning: [default] QtWarning: QMetaMethod::invokeMethod: return type mismatch for method ScriptableProxy::selectedItemsData(): cannot convert from QList<QVariantMap> to QList<QMap<QString,QVariant>> during invocation
ERROR: Bad scriptable proxy slot call: selectedItemsData()
Warning: [default] QtWarning: QMetaMethod::invokeMethod: return type mismatch for method ScriptableProxy::selectedItemsData(): cannot convert from QList<QVariantMap> to QList<QMap<QString,QVariant>> during invocation
ERROR: Bad scriptable proxy slot call: selectedItemsData()
Warning: [default] QtWarning: QMetaMethod::invokeMethod: return type mismatch for method ScriptableProxy::selectedItemsData(): cannot convert from QList<QVariantMap> to QList<QMap<QString,QVariant>> during invocation
ERROR: Bad scriptable proxy slot call: selectedItemsData()
Warning: [default] QtWarning: QMetaMethod::invokeMethod: return type mismatch for method ScriptableProxy::selectedItemsData(): cannot convert from QList<QVariantMap> to QList<QMap<QString,QVariant>> during invocation
ERROR: Bad scriptable proxy slot call: selectedItemsData()
```

and repeat when something is copied

**Comment by hluk** [comment]
```
> Warning: [default] QtWarning: QMetaMethod::invokeMethod: return type mismatch for method ScriptableProxy::selectedItemsData(): cannot convert from QList<QVariantMap> to QList<QMap<QString,QVariant>> during invocation
> ERROR: Bad scriptable proxy slot call: selectedItemsData()
```

Hmm, not sure why that should be a problem, `QVariantMap` is alias for `QMap<QString, QVariant>`. :thinking:

**Comment by hluk** [comment]
Maybe removing `Q_DECLARE_METATYPE(QVector<QVariantMap>)` (from `src/scriptable/scriptableproxy.cpp`) helps.

It would be great if I can easily verify it, but there is only Qt 6.2.4 available in the CI image (`ubuntu-22.04`).

**Comment by Artturin** [comment]
still getting the same 

```
Warning: [default] QtWarning: QMetaMethod::invokeMethod: return type mismatch for method ScriptableProxy::selectedItemsData(): cannot convert from QList<QVariantMap> to QList<QMap<QString,QVariant>> during invocation
ERROR: Bad scriptable proxy slot call: selectedItemsData()
Warning: [default] QtWarning: QMetaMethod::invokeMethod: return type mismatch for method ScriptableProxy::selectedItemsData(): cannot convert from QList<QVariantMap> to QList<QMap<QString,QVariant>> during invocation
ERROR: Bad scriptable proxy slot call: selectedItemsData()
```

**Comment by hluk** [comment]
OK, I have wrapped the type (`QVector<QVariantMap>` in `struct VariantMapList`). Hope that works. :crossed_fingers:

**Comment by Artturin** [comment]
No warnings or errors now :+1:

**Comment by hluk** [comment]
Thanks for checking. I will merge this - not sure when I could release a new version though.

**Pull request merged**
