### PR TITLE
Windows: Fix including unofficial language in installer

### LINKED ISSUE #2313: Missing Korean in the installer
The copyq.iss contains Korean translation, but Korean is not displayed when installing it.

Isn't it because Korea.iss is missing?

https://github.com/jrsoftware/issrc/blob/main/Files/Languages/Unofficial/Korean.isl
Or 
[INNO Setup - Korean.zip](https://github.com/hluk/CopyQ/files/11150093/INNO.Setup.-.Korean.zip)

copuq-insta

CopyQ 7.0.0
Windows 11 /10

### PR DESCRIPTION
**Pull request by hluk**
Fixes #2313

### CODE REVIEW

**Comment by hluk** [comment]
Downloading the message file to Inno Setup installation folder ("Languages" subfolder) does not seem to work - the language does not show up in the installator.

Build logs:

```
...
Determining language code pages
Parsing [Languages] section, line 51
   Reading file: c:\program files (x86)\inno setup 6\Default.isl
Parsing [Languages] section, line 52
   Reading file: c:\program files (x86)\inno setup 6\Languages\Czech.isl
Parsing [Languages] section, line 53
   Reading file: c:\program files (x86)\inno setup 6\Languages\German.isl
Parsing [Languages] section, line 54
   Reading file: c:\program files (x86)\inno setup 6\Languages\Spanish.isl
Parsing [Languages] section, line 55
   Reading file: c:\program files (x86)\inno setup 6\Languages\Italian.isl
Parsing [Languages] section, line 56
   Reading file: c:\program files (x86)\inno setup 6\Languages\Korean.isl
   Messages in script file
Reading default messages from Default.isl
Parsing [Languages] section, line 51
   Reading file: c:\program files (x86)\inno setup 6\Default.isl
Parsing [Languages] section, line 52
   Reading file: c:\program files (x86)\inno setup 6\Languages\Czech.isl
Parsing [Languages] section, line 53
   Reading file: c:\program files (x86)\inno setup 6\Languages\German.isl
Parsing [Languages] section, line 54
   Reading file: c:\program files (x86)\inno setup 6\Languages\Spanish.isl
Parsing [Languages] section, line 55
   Reading file: c:\program files (x86)\inno setup 6\Languages\Italian.isl
Parsing [Languages] section, line 56
   Reading file: c:\program files (x86)\inno setup 6\Languages\Korean.isl
Parsing [LangOptions], [Messages], and [CustomMessages] sections
   Messages in script file
Reading [Code] section
Parsing [Types] section, line 121
...
```

**Comment by hluk** [comment]
Including the file with `#include` does not work either. No idea how to do this.

**Comment by VenusGirl** [comment]
Is the version of inno setup 6 currently in use 6.10+ or higher?

A lower version may not result in 6.10+ or higher scripts.
You should then use 6.10- or lower scripts.

[INNO Setup - Korean5.zip](https://github.com/hluk/CopyQ/files/11185065/INNO.Setup.-.Korean5.zip)

**Comment by hluk** [comment]
> Is the version of inno setup 6 currently in use 6.10+ or higher?

The version is InnoSetup v6.2.2 (installed from Chocolatey). It seems to be the latest version: https://jrsoftware.org/isdl.php

I cannot find version 6.10 or higher.

**Comment by VenusGirl** [comment]
InnoSetup v6.2.2 is the latest version.

**Comment by hluk** [comment]
I think the build script did not download the isl file properly; fixing in #2326.

**Pull request closed without merging**
